### PisoControllerRest.registrarVehiculo
POST http://localhost:8080/gestionParqueaderos/registrarVehiculo

Content-Type: application/json

{
    "id": 1 
}
### crear VEhiculo
POST 127.0.0.1:8080/gestionParqueaderos/crearVehiculo

Content-Type: application/json

{
    "id": 1 
}
