### PisoControllerRest.registrarVehiculo
POST http://localhost:8090/gestionParqueaderos/registrarVehiculo?idPiso=1
Content-Type: application/json

{
    
    "id": 1 
}
### crear VEhiculo
POST http://localhost:8090/gestionParqueaderos/crearVehiculo
Content-Type: application/json

{
    "id": 2
}

###obtener pisos por tipo
GET http://localhost:8090/gestionParqueaderos/pisosPorTipoVehiculo/B
