### PisoControllerRest.registrarVehiculo
POST http://localhost:8090/gestionParqueaderos/pisos/registrarVehiculo?idPiso=2
Content-Type: application/json

{
    "id":10,
    "placa": "cosa"
}
### crear VEhiculo
POST http://localhost:8090/gestionParqueaderos/crearVehiculo
Content-Type: application/json

{
    "id": 10,
    "placa": "cosa"
}

###obtener pisos por tipo
GET http://localhost:8090/gestionParqueaderos/pisosPorTipoVehiculo/B

### obtener cobro
GET http://localhost:8090/gestionParqueaderos/registrarSalida/1

###obtener lista de pisos
GET http://localhost:8090/gestionParqueaderos/pisos

###agregar persona
POST http://localhost:8090/usuario/add
Content-Type: application/json

{
    "nombre": "NombreUsuario",
    "contrasenia": "ContraseniaSegura",
    "correo": "usuario@example.com",
    "rol": "usuario"
}
###Login Usuario
POST http://localhost:8090/usuario/login
Content-Type: application/json

{
    "contrasenia": "ContraseniaSegura",
    "correo": "usuario@example.com"
}

###agregar nuevo tipo Vehiculo
POST http://localhost:8090/gestionParqueaderos/tipoVehiculo/save
Content-Type: application/json

{
    "tipo": "A",
    "tarifa": 25,
    "area": 100,
    "dia": "Lunes"
}